// This file is generated by scripts/generate-plugin-registry.js
// Do not edit manually.

import { ChatLogManagerModule } from './chat-log-manager/chat-log-manager.module';
import { ChatMessageActionModule } from './chat-message-action/chat-message-action.module';
import { CombatFlowModule } from './combat-flow/combat-flow.module';
import { CutInModule } from './cut-in/cut-in.module';
import { DynamicStandPluginModule } from './dynamic-stand/dynamic-stand.module';
import { LogoutModule } from './logout/logout.module';
import { RollCallModule } from './roll-call/roll-call.module';
import { RollResultChartModule } from './roll-result-chart/roll-result-chart.module';
import { SettingsModule } from './settings/settings.module';
import { SimpleAlarmModule } from './simple-alarm/simple-alarm.module';
import { TargetSelectorModule } from './target-selector/target-selector.module';

export const pluginModules = [
  ChatLogManagerModule,
  ChatMessageActionModule,
  CombatFlowModule,
  CutInModule,
  DynamicStandPluginModule,
  LogoutModule,
  RollCallModule,
  RollResultChartModule,
  SettingsModule,
  SimpleAlarmModule,
  TargetSelectorModule
];

export const isProduction = true;
