// This file is generated by scripts/generate-plugin-registry.js
// Do not edit manually.

import { AutoLayoutTestModule } from './auto-layout-test/auto-layout-test.module';
import { CharacterImageViewerModule } from './character-image-viewer/character-image-viewer.module';
import { ChatLogManagerModule } from './chat-log-manager/chat-log-manager.module';
import { ChatMessageActionModule } from './chat-message-action/chat-message-action.module';
import { ChatNotificationModule } from './chat-notification/chat-notification.module';
import { CombatFlowModule } from './combat-flow/combat-flow.module';
import { ConfigPanelTestModule } from './config-panel-test/config-panel-test.module';
import { CutInModule } from './cut-in/cut-in.module';
import { DynamicStandPluginModule } from './dynamic-stand/dynamic-stand.module';
import { HelloWorldModule } from './hello-world/hello-world.module';
import { LogoutModule } from './logout/logout.module';
import { OverlayTestPluginModule } from './overlay-test-plugin/overlay-test-plugin.module';
import { RollCallModule } from './roll-call/roll-call.module';
import { RollResultChartModule } from './roll-result-chart/roll-result-chart.module';
import { SettingsModule } from './settings/settings.module';
import { SimpleAlarmModule } from './simple-alarm/simple-alarm.module';
import { TargetSelectorModule } from './target-selector/target-selector.module';
import { TurnEngineTestModule } from './turn-engine-test/turn-engine-test.module';

export const pluginModules = [
  AutoLayoutTestModule,
  CharacterImageViewerModule,
  ChatLogManagerModule,
  ChatMessageActionModule,
  ChatNotificationModule,
  CombatFlowModule,
  ConfigPanelTestModule,
  CutInModule,
  DynamicStandPluginModule,
  HelloWorldModule,
  LogoutModule,
  OverlayTestPluginModule,
  RollCallModule,
  RollResultChartModule,
  SettingsModule,
  SimpleAlarmModule,
  TargetSelectorModule,
  TurnEngineTestModule
];

export const isProduction = false;
